#ifndef __CPP_EVENTS__ATOMIC_REFERENCE_COUNTER__HPP
#define __CPP_EVENTS__ATOMIC_REFERENCE_COUNTER__HPP

#include "Config.hpp"
#include PLATFORM_PATH(PlatformSpecific_AtomicReferenceCounter.hpp)

#endif //__CPP_EVENTS__ATOMIC_REFERENCE_COUNTER__HPP